config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "pages#index"

  get  "pages/index"
  get  "balance",       to: "pages#balance"
  post "set_year",      to: "pages#set_year"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  resources :users, except: [ :new, :create ]  # <-- para no duplicar /users/new (sign_up)

  resources :addresses do
    collection do
      get  :results    # acción que mostrará los datos filtrados
    end
  end

  resources :bills do
    collection do
      post :import
    end
  end

  resources :deposits do
    collection do
      post :import
      get  :results    # acción que mostrará los datos filtrados
    end
  end

  resources :apartments do
    collection do
      post :import
      get  :results    # acción que mostrará los datos filtrados
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :user

  validates :amount, numericality: { only_integer: true, other_than: 0 }

  enum :tipo_egreso,
        [ :egreso_default,
          :egreso_1,
          :egreso_2,
          :egreso_3,
          :egreso_4,
          :egreso_5 ]
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin

  before_action :set_bill, only: %i[ show edit update destroy ]

  def import
    if params[:file].blank?
      flash[:alert] = "DEBE SELECCIONAR UN ARCHIVO"
      redirect_to bills_path
      return
    end

    importer = ImportBillsFromExcel.new(params[:file])
    importer.call

    if importer.errors.any?
      flash[:alert] = "#{importer.failed.count} REGISTROS NO IMPORTADOS"
      flash[:import_errors] = importer.errors
    else
      flash[:notice] = "IMPORTACIÓN COMPLETADA EXITOSAMENTE"
    end
    redirect_to bills_path
  end

  # GET /bills or /bills.json
  def index
    # Año ya lo tengo definido
    year = selected_year

    from_month = params[:from_month].to_i
    to_month = params[:to_month].to_i

    from_month = 1 unless (1..12).include?(from_month)
    to_month = 12 unless (1..12).include?(to_month)

    @from_date = Date.new(year, from_month, 1)
    @to_date = Date.new(year, to_month, -1) # último día del mes

    # @bills = current_user.bills.where(date: @from_date..@to_date).order(date: :asc)
    @bills = Bill.where(date: @from_date..@to_date).order(date: :asc, created_at: :asc)

    @grouping = params[:grouping] ||= "by_month"

    case params[:grouping]
    when "by_month"
      @bills_by_month = @bills.group_by { |b| b.date.beginning_of_month }
    else # by_type
      orden_tipo_egreso = {
        "egreso_remuneracion" => 1,
        "egreso_util_aseo"    => 2,
        "egreso_gasto_basico" => 3,
        "egreso_mantencion"   => 4,
        "egreso_otro"         => 5
      }
      @bills_by_month = @bills.group_by(&:tipo_egreso).sort_by { |tipo, _| orden_tipo_egreso[tipo] || 99 }
    end

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Egresos",
               template: "bills/index",
               encoding: "UTF-8",
               layout: "pdf",
               orientation: "Portrait",
               page_size: "Letter"
      end
    end
  end

  # GET /bills/1 or /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = current_user.bills.new
    @bill.date ||= Date.today # Asigna la fecha de hoy
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills or /bills.json
  def create
    @bill = current_user.bills.new(bill_params)
    @bill.user_id = current_user.id

    respond_to do |format|
      if @bill.save
        flash[:notice] = "EGRESO REGISTRADO"
        format.html { redirect_to filtered_redirect }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1 or /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        flash[:notice] = "EGRESO ACTUALIZADO"
        format.html { redirect_to filtered_redirect }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1 or /bills/1.json
  def destroy
    @bill.destroy!
    flash[:notice] = "EGRESO ELIMINADO"
    respond_to do |format|
      format.html { redirect_to filtered_redirect, status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      # @bill = current_user.bills.find(params[:id])
      @bill = Bill.find(params[:id])
    end

    def filtered_redirect
      allowed_params = %i[from_month to_month grouping]
      filtered = params.slice(*allowed_params).to_unsafe_h.compact_blank
      bills_path(filtered)
    end

    # Only allow a list of trusted parameters through.
    def bill_params
      params.require(:bill).permit(:date, :tipo_egreso, :comment, :amount, :user_id)
    end
end

app/helpers/bills_helper.rb
module BillsHelper
  def tipo_egreso_humano(tipo)
    {
      "egreso_1" => "Rendición",
      "egreso_2" => "Activo fijo",
      "egreso_3" => "Traspaso Banco → Temp",
      "egreso_4" => "Traspaso Caja  → Pago",
      "egreso_5" => "Otro"
    }[tipo] || tipo.to_s.humanize
  end
end

app/views/bills/_bill.html.erb
<div id="<%= dom_id bill %>">
  <p>
    <strong>Date:</strong>
    <%= bill.date %>
  </p>

  <p>
    <strong>Tipo ingreso:</strong>
    <%= bill.tipo_ingreso %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= bill.comment %>
  </p>

  <p>
    <strong>User:</strong>
    <%= bill.user_id %>
  </p>

</div>

app/views/bills/_form.html.erb
<%= form_with(model: bill) do |form| %>

  <%= hidden_field_tag :from_month, params[:from_month] || 1 %>
  <%= hidden_field_tag :to_month, params[:to_month] || 12 %>
  <%= hidden_field_tag :grouping, params[:grouping] %>

  <% if bill.errors.any? %>
    <div style="color: red">
      <% if bill.errors.count == 1 %>
        <h4>Se encontró <%= bill.errors.count %> error </h4>
      <% else %>
        <h4>Se encontraron <%= bill.errors.count %> errores </h4>
      <% end %>
      <ul>
        <% bill.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="my-2">
    <%= form.label :date, "Fecha" %><br>
      <%if action_name == "new" %>
        <%= form.date_field :date, value: Date.today, required: true, class: "ps-2 col-5 col-sm-2 border border-2 border-secondary-subtle rounded", style:"height: 35px" %>
      <% else %>
        <%= form.date_field :date, required: true, class: "ps-2 col-5 col-sm-2 border border-2 border-secondary-subtle rounded", style:"height: 35px" %>
      <% end %>
  </div>

  Concepto del Egreso<br>
  <div class="ps-2 col-11 col-sm-8 btn-group border border-2 order-secondary-subtle" data-toggle="buttons">
    <%= form.radio_button :tipo_egreso, "egreso_1", checked: true, id: "tipo_egreso_1" %>
    <%= form.label :tipo_egreso, "Rendición", value: "egreso_1", class: "btn", for: "tipo_egreso_1" %>

    <%= form.radio_button :tipo_egreso, "egreso_2", id: "tipo_egreso_2" %>
    <%= form.label :tipo_egreso, "Activo Fijo", value: "egreso_2", class: "btn", for: "tipo_egreso_2" %>

    <%= form.radio_button :tipo_egreso, "egreso_3", id: "tipo_egreso_3" %>
    <%= form.label :tipo_egreso, "Traspaso Banco → Temp", value: "egreso_3", class: "btn", for: "tipo_egreso_3" %>

    <%= form.radio_button :tipo_egreso, "egreso_4", id: "tipo_egreso_4" %>
    <%= form.label :tipo_egreso, "Traspaso Caja → Pago", value: "egreso_4", class: "btn", for: "tipo_egreso_4" %>

    <%= form.radio_button :tipo_egreso, "egreso_5", id: "tipo_egreso_5" %>
    <%= form.label :tipo_egreso, "Otro", value: "egreso_5", class: "btn", for: "tipo_egreso_5" %>
  </div>

  <div class="field my-2">
    <%= form.label :comment, "Comentario" %><br />
    <%= form.text_area :comment, required: true, class: "ps-2 col-11 col-sm-8 border border-2 border-secondary-subtle", rows: 3 %>
  </div>

  <div class="my-2">
    <%= form.label :amount, "Cantidad" %><br>
    <%= form.text_field :amount, required: true, class: "ps-2 col-5 col-sm-2 border border-2 border-secondary-subtle rounded", style:"height: 35px", id: "amount_input", data: { original_value: form.object.amount.present? ? form.object.amount.to_s.gsub(/\D/, "") : ""
    }  %>
  </div>
  <br>

  <div>
    <% if action_name == "new" %>
      <%= form.submit "Registrar", class: "btn btn-info col-4 col-sm-3 col-md-2 col-lg-1" %>
      <div class="py-2">
        <%= link_to "Regresar", bills_path(from_month: params[:from_month], to_month: params[:to_month]), class: "btn btn-light border border-2 btn-ancho col-4 col-sm-3 col-md-2 col-lg-1" %>
      </div>
    <% else %>
      <%= form.submit "Actualizar", class: "btn btn-info col-4 col-sm-3 col-md-2 col-lg-1" %>
      <div class="py-2">
        <%= link_to "Regresar", bills_path(from_month: params[:from_month], to_month: params[:to_month]), class: "btn btn-light border border-2 btn-ancho col-4 col-sm-3 col-md-2 col-lg-1" %>
      </div>
     <% end %>
  </div>

<% end %>

<script>
  function initBillFormScript() {
    // === CANTIDAD (AMOUNT) ===
    const amountInput = document.getElementById("amount_input");

    if (amountInput && !amountInput.dataset.listenerAdded) {
      console.log("Escuchando en CANTIDAD");

      amountInput.dataset.listenerAdded = true;

      const formatCL = (value) => {
        const raw = value.replace(/\D/g, ""); // Solo números
        return new Intl.NumberFormat("es-CL", {
          minimumFractionDigits: 0,
          maximumFractionDigits: 0
        }).format(raw);
      };

      if (amountInput.value) {
        const rawValue = amountInput.value.replace(/\D/g, "");
        amountInput.dataset.originalValue = rawValue;
        amountInput.value = formatCL(rawValue);
      }

      amountInput.addEventListener("input", function () {
        const rawValue = this.value.replace(/\D/g, "");
        this.dataset.originalValue = rawValue;
        this.value = formatCL(rawValue);
      });

      if (amountInput.form) {
        amountInput.form.addEventListener("submit", function () {
          amountInput.value = amountInput.dataset.originalValue;
        });
      }
    }
  }

  document.addEventListener("turbo:load", initBillFormScript);
  document.addEventListener("turbo:render", initBillFormScript);
</script>

app/views/bills/edit.html.erb
<% content_for :title, "Editing bill" %>

<h2>Editando egreso</h2>

<%= render "form", bill: @bill %>
<br>

app/views/bills/index.html.erb
<% content_for :title, "Bills" %>

<style>
  .w-10 { width: 10%; }
  .w-15 { width: 15%; }
  .w-40 { width: 40%; }
  .w-20 { width: 20%; }
  .text-end { text-align: right; }
</style>

<%= link_to "Registrar egreso", new_bill_path(request.query_parameters), class: "mb-3 col-6 col-sm-4 col-md-2 col-lg-2 fs-5 btn bg-info text-white" %>

<%= form_with url: bills_path, method: :get, local: true do %>
  <div class="row mb-3 col-12 col-md-12 ms-0 border border-2 border-secondary-subtle rounded">

    <!-- Columna 1: Fecha -->
    <div class="col-md-3 my-1">
      <%= label_tag :from_month, "Desde" %>
        <%= select_tag :from_month,
             options_for_select((1..12).map { |m| [I18n.t("date.month_names")[m], m] }, @from_date.month),
             class: "form-control mb-1 border border-2 border-secondary-subtle rounded" %>
      <%= label_tag :to_month, "Hasta" %>
      <%= select_tag :to_month,
            options_for_select((1..12).map { |m| [I18n.t("date.month_names")[m], m] }, @to_date.month),
            class: "form-control mb-1 border border-2 border-secondary-subtle rounded" %>
    </div>

    <!-- Columna 2: Agrupar por -->
    <div class="col-md-3 my-1">
      <%= label_tag :grouping, "Agrupar por" %><br>
      <div class="form-check">
        <%= radio_button_tag :grouping, "by_month", params[:grouping] == "by_month", id: "grouping_by_month", class: "form-check-input border border-2 border-secondary-subtle rounded" %>
        <%= label_tag :grouping_by_month, "Mes", class: "form-check-label" %>
      </div>
      <div class="form-check">
        <%= radio_button_tag :grouping, "by_type", params[:grouping] == "by_type", id: "grouping_by_type", class: "form-check-input border border-2 border-secondary-subtle rounded" %>
        <%= label_tag :grouping_by_type, "Tipo de egreso", class: "form-check-label" %>
      </div>
    </div>

    <!-- Columna 3: Acciones -->
    <div class="col-md-3 mt-4 d-flex flex-column justify-content-start">
      <%= submit_tag "Filtrar", class: "col-6 mb-2 btn btn-primary" %>
      <%= link_to "Limpiar", bills_path, class: "col-6 mb-2 btn btn-secondary" %>
    </div>

  </div>
<% end %>

<% if current_user.admin? %>
  <div class="mt-2 my-1 border border-2 border-secondary-subtle rounded">
    <%= form_with url: import_bills_path, method: :post, local: true, html: { multipart: true } do |f| %>
      <h5 class="mt-1 ms-2">Importar datos desde archivo Excel</h5>
      <div class="ms-2">
        <%= f.label :file, "Archivo" %>
        <%= f.file_field :file, class: "ps-2 py-1 col-11 col-md-6 border border-2 border-secondary-subtle rounded", style:"height: 40px" %>
      </div>
      <div>
        <%= f.submit "Importar", class: "col-6 col-sm-4 col-md-2 col-lg-2 ms-2 my-2 btn btn-secondary" %>
      </div>
    <% end %>
  </div>
<% end %>

<div class="py-3">
  <%= link_to "Exportar PDF", bills_path(format: :pdf, from_month: params[:from_month], from_year: params[:from_year], to_month: params[:to_month], to_year: params[:to_year], grouping: params[:grouping]), class: "col-4 col-sm-3 col-md-2 col-lg-2 btn btn-secondary" %>
</div>

<h2> Detalle de egresos</h2>
<br>

<% total_general = 0 %>

<div data-controller="confirm-delete-modal">

  <% @bills_by_month.each do |month_date, bills| %>
    <!-- Título del grupo -->
    <% if params[:grouping] == "by_type" %>
      <% label = case month_date
          when "egreso_1" then "Rendición"
          when "egreso_2" then "Activo fijo"
          when "egreso_3" then "Traspaso Banco → Caja"
          when "egreso_4" then "Traspaso Caja  → Pago"
          when "egreso_5" then "Otros gastos"
          else "Otros"
      end %>
      <h4><%= label %></h4>
    <% else %>
      <h4><%= l(month_date, format: "%B %Y").capitalize %></h4>
    <% end %>

    <div class="table-responsive">
      <table class="table table-bordered table-striped">
        <thead>
          <tr class="table-primary">
            <th scope="col" class="w-10">FECHA</th>
            <th scope="col" class="w-40">COMENTARIO</th>
            <th scope="col" class="w-15">TIPO EGRESO</th>
            <th scope="col" class="w-15 text-end">MONTO</th>
            <th scope="col" class="w-10 text-center">ACCIÓN</th>
          </tr>
        </thead>

        <tbody>
          <% subtotal = 0 %>
          <% bills.each do |bill| %>
            <tr>
              <td class="text-start">
                <div class="d-flex">
                  <%= link_to bill.date.strftime("%d-%m-%Y"), edit_bill_path(bill, request.query_parameters), data: { turbo: false }, class: "btn btn-primary btn-sm" %>
                </div>
              </td>
              <td class="text-start"><%= bill.comment %></td>
              <td class="text-start">
                <% label = case bill.tipo_egreso
                  when "egreso_1" then "Rendición"
                  when "egreso_2" then "Activo fijo"
                  when "egreso_3" then "Traspaso Banco → Caja"
                  when "egreso_4" then "Traspaso Caja  → Pago"
                  when "egreso_5" then "Otros gastos"
                  else "Otros"
                end %>
                <%= label %>
              </td>
              <td class="text-end">
                <% subtotal += bill.amount %>
                <% total_general += bill.amount %>
                <%= number_to_currency(bill.amount, unit: "$", delimiter: ".", precision: 0, format: "%u%n") %>
              </td>
              <td class="text-center">
                <%= button_to bill_path(bill),
                      method: :delete,
                      data: { turbo: false },
                      form: { id: "deleteForm-#{bill.id}" },
                      class: "btn btn-danger btn-sm d-none" do %>
                  <i class="fa-solid fa-trash"></i>
                <% end %>
                <button type="button"
                        class="btn btn-danger btn-sm"
                        data-bill-form="deleteForm-<%= bill.id %>"
                        data-action="click->confirm-delete-modal#showModal">
                  <i class="fa-solid fa-trash"></i>
                </button>
              </td>
            </tr>
          <% end %>

          <!-- Subtotal -->
          <tr>

            <td colspan="3" class="text-end fw-bold">
              Subtotal 
              <% if params[:grouping] == "by_type" %>
                <% label = case month_date
                  when "egreso_1" then "Rendición"
                  when "egreso_2" then "Activo fijo"
                  when "egreso_3" then "Traspaso Banco → Caja"
                  when "egreso_4" then "Traspaso Caja  → Pago"
                  when "egreso_5" then "Otros gastos"
                  else "Otros" 
                end %>
                <%= label %>
              <% else %>
                <%= l(month_date, format: "%B %Y").capitalize %>
              <% end %>
            </td>

            <td class="text-end fw-bold"><%= number_to_currency(subtotal, unit: "$", delimiter: ".", precision: 0, format: "%u%n") %></td>
            <td></td>
          </tr>
        </tbody>
      </table>
    </div>
    <br>
  <% end %>

  <!-- Total general -->
  <% if total_general > 0 %>
    <div class="mb-3">
      <h4 class="text-start">
        TOTAL DEL PERIODO: <%= number_to_currency(total_general, unit: "$", delimiter: ".", precision: 0, format: "%u%n") %>
      </h4>
      <br>
    </div>
  <% end %>

  <!-- Modal de confirmación -->
  <div class="modal fade"
       id="confirmDeleteModal"
       tabindex="-1"
      aria-labelledby="confirmDeleteModalLabel"
      aria-hidden="true"
      data-confirm-delete-modal-target="modal">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="confirmDeleteModalLabel">Confirma eliminación</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
        </div>
        <div class="modal-body">
          ¿Estás seguro de querer eliminar este registro?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <button type="button"
                  class="btn btn-danger"
                  data-confirm-delete-modal-target="confirm"
                  data-action="click->confirm-delete-modal#confirmDelete">
            Eliminar
          </button>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/bills/index.pdf.erb
<h1>Egresos</h1>

<% if @bills.count == 0 %>
  <h2>No existen egresos registrados</h2>
<% else %>
  <% total_general = 0 %>

  <% @bills_by_month.each do |month_date, bills| %>
    <!-- Título del mes -->
    <h2><%= l(month_date, format: "%B %Y").capitalize %></h2>

    <table style="width: 90%; border-collapse: collapse; font-size: 12px; margin-bottom: 20px;">
      <thead>
        <tr>
          <th style="text-align: left; width: 15%; font-size: 14px">FECHA</th>
          <th style="text-align: left; width: 50%; font-size: 14px">COMENTARIO</th>
          <th style="text-align: left; width: 20%; font-size: 14px">TIPO</th>
          <th style="text-align: right; width: 15%; font-size: 14px">CANTIDAD</th>
        </tr>
        <tr>
          <td colspan="4">
            <div style="width: 100%; height: 1px; background-color: #000; margin-top: 5px; margin-bottom: 5px"></div>
          </td>
        </tr>
      </thead>
      <tbody>
        <% subtotal = 0 %>
        <% bills.each do |bill| %>
          <tr>
            <td style="text-align: left; font-size: 14px "><%= bill.date.strftime("%d-%m-%Y") %></td>
            <td style="text-align: left; font-size: 14px"><%= bill.comment %></td>
            <td style="text-align: left; font-size: 14px">
              <% case bill.tipo_egreso
                  when "egreso_1" then label = "Rendición"
                  when "egreso_2" then label = "Activo fijo"
                  when "egreso_3" then label = "Traspaso Banco → Caja"
                  when "egreso_4" then label = "Traspaso Caja  → Pago"
                  when "egreso_5" then label = "Otros gastos"
                  else label = "Otros"
              end %>
              <%= label %>
            </td>
            <td style="text-align: right; font-size: 14px">
              <% subtotal += bill.amount %>
              <% total_general += bill.amount %>
              <%= number_to_currency(bill.amount, unit: "$", delimiter: ".", precision: 0, format: "%u%n") %>
            </td>
          </tr>
        <% end %>
        <tr>
          <td colspan="4"> 
            <div style="width: 100%; height: 1px; background-color: #000; margin-top: 5px; margin-bottom: 5px"></div>
          </td>
        </tr>

        <!-- Subtotal mensual -->
        <tr>
          <td colspan="3" style="text-align: right; font-size: 14px;margin-top: 5px; margin-bottom: 5px"><strong>Subtotal <%= l(month_date, format: "%B %Y").capitalize %></strong></td>
          <td style="text-align: right; font-size: 14px"><strong><%= number_to_currency(subtotal, unit: "$", delimiter: ".", precision: 0, format: "%u%n") %></strong></td>
        </tr>
      </tbody>
    </table>
    <br>
  <% end %>

  <!-- Total general al final de todo -->
  <div style="width: 90%; border-bottom: 1px solid #000; margin-top: 5px; margin-bottom: 2px;"></div>
  <div style="width: 90%; border-bottom: 1px solid #000; margin-bottom: 5px"></div>
  <div style="font-size: 14px; margin-top: 5px">
      <strong>TOTAL GENERAL <%= number_to_currency(total_general, unit: "$", delimiter: ".", precision: 0, format: "%u%n") %></strong>
  </div>
<% end %>

app/views/bills/new.html.erb
<% content_for :title, "New bill" %>

<h2>Registro de egreso</h2>

<%= render "form", bill: @bill %>
<br>

app/views/bills/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bill %>

<div>
  <%= link_to "Edit this bill", edit_bill_path(@bill) %> |
  <%= link_to "Back to bills", bills_path %>

  <%= button_to "Destroy this bill", @bill, method: :delete %>
</div>